// Generated by Haxe 4.3.3
#include <hxcpp.h>

#ifndef INCLUDED_4dbe585c96d08098
#define INCLUDED_4dbe585c96d08098
#include "genesis.h"
#endif
#ifndef INCLUDED_genesis__GsCommandList_GsCommandList_Impl_
#include <genesis/_GsCommandList/GsCommandList_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_12_begin,"genesis._GsCommandList.GsCommandList_Impl_","begin",0xfd3210ae,"genesis._GsCommandList.GsCommandList_Impl_.begin","genesis/GsCommandList.hx",12,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_17_end,"genesis._GsCommandList.GsCommandList_Impl_","end",0x42dc0f20,"genesis._GsCommandList.GsCommandList_Impl_.end","genesis/GsCommandList.hx",17,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_22_submit,"genesis._GsCommandList.GsCommandList_Impl_","submit",0x8dcbe5f3,"genesis._GsCommandList.GsCommandList_Impl_.submit","genesis/GsCommandList.hx",22,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_27_clear,"genesis._GsCommandList.GsCommandList_Impl_","clear",0x95379812,"genesis._GsCommandList.GsCommandList_Impl_.clear","genesis/GsCommandList.hx",27,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_32_setViewport,"genesis._GsCommandList.GsCommandList_Impl_","setViewport",0xf1296e6d,"genesis._GsCommandList.GsCommandList_Impl_.setViewport","genesis/GsCommandList.hx",32,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_37_discard,"genesis._GsCommandList.GsCommandList_Impl_","discard",0x0bc0abe3,"genesis._GsCommandList.GsCommandList_Impl_.discard","genesis/GsCommandList.hx",37,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_42_usePipeline,"genesis._GsCommandList.GsCommandList_Impl_","usePipeline",0xc9b21ace,"genesis._GsCommandList.GsCommandList_Impl_.usePipeline","genesis/GsCommandList.hx",42,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_47_useBuffer,"genesis._GsCommandList.GsCommandList_Impl_","useBuffer",0x405199ac,"genesis._GsCommandList.GsCommandList_Impl_.useBuffer","genesis/GsCommandList.hx",47,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_52_useTexture,"genesis._GsCommandList.GsCommandList_Impl_","useTexture",0xf46502af,"genesis._GsCommandList.GsCommandList_Impl_.useTexture","genesis/GsCommandList.hx",52,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_57_drawArrays,"genesis._GsCommandList.GsCommandList_Impl_","drawArrays",0x4c850b39,"genesis._GsCommandList.GsCommandList_Impl_.drawArrays","genesis/GsCommandList.hx",57,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_62_drawIndexed,"genesis._GsCommandList.GsCommandList_Impl_","drawIndexed",0x4e2af892,"genesis._GsCommandList.GsCommandList_Impl_.drawIndexed","genesis/GsCommandList.hx",62,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_67_setScissor,"genesis._GsCommandList.GsCommandList_Impl_","setScissor",0xaa9763f5,"genesis._GsCommandList.GsCommandList_Impl_.setScissor","genesis/GsCommandList.hx",67,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_72_disableScissor,"genesis._GsCommandList.GsCommandList_Impl_","disableScissor",0x2e85d3ef,"genesis._GsCommandList.GsCommandList_Impl_.disableScissor","genesis/GsCommandList.hx",72,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_77_setInt,"genesis._GsCommandList.GsCommandList_Impl_","setInt",0x632d2848,"genesis._GsCommandList.GsCommandList_Impl_.setInt","genesis/GsCommandList.hx",77,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_82_setFloat,"genesis._GsCommandList.GsCommandList_Impl_","setFloat",0xab742935,"genesis._GsCommandList.GsCommandList_Impl_.setFloat","genesis/GsCommandList.hx",82,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_87_setVec2,"genesis._GsCommandList.GsCommandList_Impl_","setVec2",0x6ce6f9e5,"genesis._GsCommandList.GsCommandList_Impl_.setVec2","genesis/GsCommandList.hx",87,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_92_setVec3,"genesis._GsCommandList.GsCommandList_Impl_","setVec3",0x6ce6f9e6,"genesis._GsCommandList.GsCommandList_Impl_.setVec3","genesis/GsCommandList.hx",92,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_97_setVec4,"genesis._GsCommandList.GsCommandList_Impl_","setVec4",0x6ce6f9e7,"genesis._GsCommandList.GsCommandList_Impl_.setVec4","genesis/GsCommandList.hx",97,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_102_setMat4,"genesis._GsCommandList.GsCommandList_Impl_","setMat4",0x66f1141b,"genesis._GsCommandList.GsCommandList_Impl_.setMat4","genesis/GsCommandList.hx",102,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_113_setMat4Array,"genesis._GsCommandList.GsCommandList_Impl_","setMat4Array",0x7706077e,"genesis._GsCommandList.GsCommandList_Impl_.setMat4Array","genesis/GsCommandList.hx",113,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_124_copyTexture,"genesis._GsCommandList.GsCommandList_Impl_","copyTexture",0x19189deb,"genesis._GsCommandList.GsCommandList_Impl_.copyTexture","genesis/GsCommandList.hx",124,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_129_resolveTexture,"genesis._GsCommandList.GsCommandList_Impl_","resolveTexture",0x2378b42a,"genesis._GsCommandList.GsCommandList_Impl_.resolveTexture","genesis/GsCommandList.hx",129,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_134_copyTexturePartial,"genesis._GsCommandList.GsCommandList_Impl_","copyTexturePartial",0xe331c4d6,"genesis._GsCommandList.GsCommandList_Impl_.copyTexturePartial","genesis/GsCommandList.hx",134,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_139_generateMipmaps,"genesis._GsCommandList.GsCommandList_Impl_","generateMipmaps",0xc06351fb,"genesis._GsCommandList.GsCommandList_Impl_.generateMipmaps","genesis/GsCommandList.hx",139,0x1bd69f48)
HX_LOCAL_STACK_FRAME(_hx_pos_e1b6125b338a51d3_145_destroy,"genesis._GsCommandList.GsCommandList_Impl_","destroy",0x7d9cbebf,"genesis._GsCommandList.GsCommandList_Impl_.destroy","genesis/GsCommandList.hx",145,0x1bd69f48)
namespace genesis{
namespace _GsCommandList{

void GsCommandList_Impl__obj::__construct() { }

Dynamic GsCommandList_Impl__obj::__CreateEmpty() { return new GsCommandList_Impl__obj; }

void *GsCommandList_Impl__obj::_hx_vtable = 0;

Dynamic GsCommandList_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< GsCommandList_Impl__obj > _hx_result = new GsCommandList_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool GsCommandList_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x27296737;
}

 GsCommandList * GsCommandList_Impl__obj::begin( GsCommandList * this1){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_12_begin)
HXLINE(  13)		gs_command_list_begin(this1);
HXLINE(  14)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::end( GsCommandList * this1){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_17_end)
HXLINE(  18)		gs_command_list_end(this1);
HXLINE(  19)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::submit( GsCommandList * this1){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_22_submit)
HXLINE(  23)		gs_command_list_submit(this1);
HXLINE(  24)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::clear( GsCommandList * this1,int flags,::hx::Null< Float >  __o_r,::hx::Null< Float >  __o_g,::hx::Null< Float >  __o_b,::hx::Null< Float >  __o_a){
            		Float r = __o_r.Default(0);
            		Float g = __o_g.Default(0);
            		Float b = __o_b.Default(0);
            		Float a = __o_a.Default(1);
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_27_clear)
HXLINE(  28)		gs_clear(this1,(GsClearFlags)flags,r,g,b,a);
HXLINE(  29)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::setViewport( GsCommandList * this1,int x,int y,int width,int height){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_32_setViewport)
HXLINE(  33)		gs_set_viewport(this1,x,y,width,height);
HXLINE(  34)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::discard( GsCommandList * this1){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_37_discard)
HXLINE(  38)		gs_command_list_clear(this1);
HXLINE(  39)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::usePipeline( GsCommandList * this1, GsPipeline * pipeline){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_42_usePipeline)
HXLINE(  43)		gs_use_pipeline(this1,pipeline);
HXLINE(  44)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::useBuffer( GsCommandList * this1, GsBuffer * buffer){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_47_useBuffer)
HXLINE(  48)		gs_use_buffer(this1,buffer);
HXLINE(  49)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::useTexture( GsCommandList * this1, GsTexture * texture,int slot){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_52_useTexture)
HXLINE(  53)		gs_use_texture(this1,texture,slot);
HXLINE(  54)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::drawArrays( GsCommandList * this1,int start,int count){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_57_drawArrays)
HXLINE(  58)		gs_draw_arrays(this1,start,count);
HXLINE(  59)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::drawIndexed( GsCommandList * this1,int count){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_62_drawIndexed)
HXLINE(  63)		gs_draw_indexed(this1,count);
HXLINE(  64)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::setScissor( GsCommandList * this1,int x,int y,int width,int height){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_67_setScissor)
HXLINE(  68)		gs_set_scissor(this1,x,y,width,height);
HXLINE(  69)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::disableScissor( GsCommandList * this1){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_72_disableScissor)
HXLINE(  73)		gs_disable_scissor(this1);
HXLINE(  74)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::setInt( GsCommandList * this1,int location,int value){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_77_setInt)
HXLINE(  78)		gs_uniform_set_int(this1,location,value);
HXLINE(  79)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::setFloat( GsCommandList * this1,int location,Float value){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_82_setFloat)
HXLINE(  83)		gs_uniform_set_float(this1,location,( (float)(value) ));
HXLINE(  84)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::setVec2( GsCommandList * this1,int location,Float x,Float y){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_87_setVec2)
HXLINE(  88)		gs_uniform_set_vec2(this1,location,( (float)(x) ),( (float)(y) ));
HXLINE(  89)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::setVec3( GsCommandList * this1,int location,Float x,Float y,Float z){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_92_setVec3)
HXLINE(  93)		gs_uniform_set_vec3(this1,location,( (float)(x) ),( (float)(y) ),( (float)(z) ));
HXLINE(  94)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::setVec4( GsCommandList * this1,int location,Float x,Float y,Float z,Float w){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_97_setVec4)
HXLINE(  98)		gs_uniform_set_vec4(this1,location,( (float)(x) ),( (float)(y) ),( (float)(z) ),( (float)(w) ));
HXLINE(  99)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::setMat4( GsCommandList * this1,int location,Float m00,Float m01,Float m02,Float m03,Float m10,Float m11,Float m12,Float m13,Float m20,Float m21,Float m22,Float m23,Float m30,Float m31,Float m32,Float m33){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_102_setMat4)
HXLINE( 103)		gs_uniform_set_mat4(this1,location,( (float)(m00) ),( (float)(m01) ),( (float)(m02) ),( (float)(m03) ),( (float)(m10) ),( (float)(m11) ),( (float)(m12) ),( (float)(m13) ),( (float)(m20) ),( (float)(m21) ),( (float)(m22) ),( (float)(m23) ),( (float)(m30) ),( (float)(m31) ),( (float)(m32) ),( (float)(m33) ));
HXLINE( 110)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::setMat4Array( GsCommandList * this1,int location,::Array< Float > data){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_113_setMat4Array)
HXLINE( 114)		gs_uniform_set_mat4(this1,location,( (float)(data->__get(0)) ),( (float)(data->__get(1)) ),( (float)(data->__get(2)) ),( (float)(data->__get(3)) ),( (float)(data->__get(4)) ),( (float)(data->__get(5)) ),( (float)(data->__get(6)) ),( (float)(data->__get(7)) ),( (float)(data->__get(8)) ),( (float)(data->__get(9)) ),( (float)(data->__get(10)) ),( (float)(data->__get(11)) ),( (float)(data->__get(12)) ),( (float)(data->__get(13)) ),( (float)(data->__get(14)) ),( (float)(data->__get(15)) ));
HXLINE( 121)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::copyTexture( GsCommandList * this1, GsTexture * src, GsTexture * dst){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_124_copyTexture)
HXLINE( 125)		gs_copy_texture(this1,src,dst);
HXLINE( 126)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::resolveTexture( GsCommandList * this1, GsTexture * src, GsTexture * dst){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_129_resolveTexture)
HXLINE( 130)		gs_resolve_texture(this1,src,dst);
HXLINE( 131)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::copyTexturePartial( GsCommandList * this1, GsTexture * src, GsTexture * dst,int srcX,int srcY,int dstX,int dstY,int width,int height){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_134_copyTexturePartial)
HXLINE( 135)		gs_copy_texture_partial(this1,src,dst,srcX,srcY,dstX,dstY,width,height);
HXLINE( 136)		return this1;
            	}


 GsCommandList * GsCommandList_Impl__obj::generateMipmaps( GsCommandList * this1, GsTexture * texture){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_139_generateMipmaps)
HXLINE( 140)		gs_generate_mipmaps(this1,texture);
HXLINE( 141)		return this1;
            	}


void GsCommandList_Impl__obj::destroy( GsCommandList * this1){
            	HX_STACKFRAME(&_hx_pos_e1b6125b338a51d3_145_destroy)
HXDLIN( 145)		gs_destroy_command_list(this1);
            	}



GsCommandList_Impl__obj::GsCommandList_Impl__obj()
{
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *GsCommandList_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *GsCommandList_Impl__obj_sStaticStorageInfo = 0;
#endif

::hx::Class GsCommandList_Impl__obj::__mClass;

void GsCommandList_Impl__obj::__register()
{
	GsCommandList_Impl__obj _hx_dummy;
	GsCommandList_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("genesis._GsCommandList.GsCommandList_Impl_",33,25,c1,fe);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< GsCommandList_Impl__obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = GsCommandList_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = GsCommandList_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace genesis
} // end namespace _GsCommandList
