// Generated by Haxe 4.3.3
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"?",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Std.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Sys.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Log.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/ds/StringMap.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/io/Bytes.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/iterators/ArrayIterator.hx",
"Main.hx",
"genesis/GsMainloop.hx",
"genesis/GsManagedData.hx",
"glfw/GLFW.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"C:\\mana25\\genesis\\Samples\\2-Textured-Quad\\?",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Std.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Sys.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Log.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\ds\\StringMap.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Bytes.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\iterators\\ArrayIterator.hx",
"C:\\mana25\\genesis\\Samples\\2-Textured-Quad\\Source\\Main.hx",
"C:\\mana25\\genesis\\Source\\genesis\\GsMainloop.hx",
"C:\\mana25\\genesis\\Source\\genesis\\GsManagedData.hx",
"C:\\Users\\mikai\\Desktop\\KawaiiFramework\\Framework\\thirdparty\\linc_glfw\\glfw\\GLFW.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Main",
"Std",
"Sys",
"genesis.GsMainloop",
"genesis._GsManagedData.GsManagedDataHolder",
"genesis._GsManagedData.GsManagedData_Impl_",
"glfw.GLFWErrorHandler",
"glfw.GLFWCharHandler",
"glfw.GLFWKeyHandler",
"glfw.GLFWMouseMoveHandler",
"glfw.GLFWMouseButtonHandler",
"glfw.GLFWMouseWheelHandler",
"glfw.GLFWJoystickHandler",
"glfw.GLFWWindowSizeHandler",
"haxe.Log",
"haxe.ds.StringMap",
"haxe.io.Bytes",
"haxe.iterators.ArrayIterator",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
