// Generated by Haxe 4.3.3
#include <hxcpp.h>

#ifndef INCLUDED_4dbe585c96d08098
#define INCLUDED_4dbe585c96d08098
#include "genesis.h"
#endif
#ifndef INCLUDED_66c800784bc86d2f
#define INCLUDED_66c800784bc86d2f
#include "linc_glfw.h"
#endif
#ifndef INCLUDED_ea389c7812b8afb8
#define INCLUDED_ea389c7812b8afb8
#include "linc_stb_image.h"
#endif
#ifndef INCLUDED_Main
#include <Main.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED_genesis_GsMainloop
#include <genesis/GsMainloop.h>
#endif
#ifndef INCLUDED_genesis__GsManagedData_GsManagedDataHolder
#include <genesis/_GsManagedData/GsManagedDataHolder.h>
#endif
#ifndef INCLUDED_genesis__GsManagedData_GsManagedData_Impl_
#include <genesis/_GsManagedData/GsManagedData_Impl_.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_e47a9afac0942eb9_19_new,"Main","new",0x6616a5cb,"Main.new","Main.hx",19,0x087e5c05)
static const int _hx_array_data_332f6459_1[] = {
	(int)0,(int)1,(int)2,(int)2,(int)3,(int)0,
};
static const float _hx_array_data_332f6459_2[] = {
	-0.5,-0.5,0.0,0.0,1.0,0.5,-0.5,0.0,1.0,1.0,0.5,0.5,0.0,1.0,0.0,-0.5,0.5,0.0,0.0,0.0,
};
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_83_initWindow,"Main","initWindow",0xee596d15,"Main.initWindow","Main.hx",83,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_111_destroyWindow,"Main","destroyWindow",0xf8fc15b5,"Main.destroyWindow","Main.hx",111,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_114_initGraphics,"Main","initGraphics",0xddf92530,"Main.initGraphics","Main.hx",114,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_169_destroyGraphics,"Main","destroyGraphics",0xd50f35d0,"Main.destroyGraphics","Main.hx",169,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_189_frame,"Main","frame",0x82b6be58,"Main.frame","Main.hx",189,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_204_loop,"Main","loop",0xec6f8e99,"Main.loop","Main.hx",204,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_217_init,"Main","init",0xea732345,"Main.init","Main.hx",217,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_224_destroy,"Main","destroy",0x88b793e5,"Main.destroy","Main.hx",224,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_230_main,"Main","main",0xed0e206e,"Main.main","Main.hx",230,0x087e5c05)

void Main_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_19_new)
HXLINE(  56)		this->fragmentShaderSource = HX_("\r\n        #version 460 core\r\n\r\n        uniform sampler2D uTexture;\r\n        in vec2 vTexCoord;\r\n        out vec4 fragColor;\r\n\r\n        void main() {\r\n            fragColor = texture(uTexture, vTexCoord);\r\n        }\r\n    ",ee,41,48,a7);
HXLINE(  34)		this->vertexShaderSource = HX_("\r\n        #version 460 core\r\n\r\n        layout(location = 0) in vec3 aPosition;\r\n        layout(location = 1) in vec2 aTexCoord;\r\n        uniform int uTime;\r\n        out vec2 vTexCoord;\r\n\r\n        void main() {\r\n            gl_Position = vec4(aPosition, 1.0);\r\n\r\n            float angle = -float(uTime) / 1000.0;\r\n            float cosAngle = cos(angle);\r\n            float sinAngle = sin(angle);\r\n\r\n            gl_Position.x = aPosition.x * cosAngle - aPosition.y * sinAngle;\r\n            gl_Position.y = aPosition.x * sinAngle + aPosition.y * cosAngle;\r\n\r\n            vTexCoord = aTexCoord;\r\n        }\r\n    ",38,47,6a,b5);
HXLINE(  29)		this->indexData = ::Array_obj< int >::fromData( _hx_array_data_332f6459_1,6);
HXLINE(  21)		this->vertexData = ::Array_obj< float >::fromData( _hx_array_data_332f6459_2,20);
            	}

Dynamic Main_obj::__CreateEmpty() { return new Main_obj; }

void *Main_obj::_hx_vtable = 0;

Dynamic Main_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Main_obj > _hx_result = new Main_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Main_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x07825a7d;
}

void Main_obj::initWindow(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_83_initWindow)
HXLINE(  84)		{
HXLINE(  84)			void();
HXDLIN(  84)			glfwInit();
            		}
HXLINE(  92)		glfwWindowHint(139265,196610);
HXLINE(  93)		glfwWindowHint(139266,2);
HXLINE(  94)		glfwWindowHint(139267,0);
HXLINE(  95)		glfwWindowHint(139271,0);
HXLINE(  96)		glfwWindowHint(131075,0);
HXLINE(  98)		{
HXLINE(  98)			void();
HXDLIN(  98)			glfwInit();
            		}
HXLINE(  99)		glfwWindowHint(131075,0);
HXLINE( 101)		::cpp::Pointer<  GLFWmonitor > tmp = null();
HXDLIN( 101)		::cpp::Pointer<  GLFWwindow > tmp1 = null();
HXDLIN( 101)		this->window = glfwCreateWindow(600,600,HX_("Genesis [2 - Textured Quad]",03,53,05,04),tmp,tmp1);
HXLINE( 102)		if (::hx::IsNull( this->window )) {
HXLINE( 103)			glfwTerminate();
HXLINE( 104)			return;
            		}
HXLINE( 107)		::cpp::Pointer<  GLFWwindow > tmp2 = this->window;
HXDLIN( 107)		glfwMakeContextCurrent(tmp2);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Main_obj,initWindow,(void))

void Main_obj::destroyWindow(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_111_destroyWindow)
HXDLIN( 111)		glfwTerminate();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Main_obj,destroyWindow,(void))

void Main_obj::initGraphics(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_114_initGraphics)
HXLINE( 116)		this->backend = gs_create_backend(gs_get_optimal_backend_type());
HXLINE( 119)		this->config = gs_create_config();
HXLINE( 120)		(*(this->config)).backend = this->backend;
HXLINE( 123)		gs_init(this->config);
HXLINE( 126)		this->commandList = gs_create_command_list();
HXLINE( 129)		this->vertexShader = gs_create_shader(GS_SHADER_TYPE_VERTEX,this->vertexShaderSource.utf8_str());
HXLINE( 130)		this->fragmentShader = gs_create_shader(GS_SHADER_TYPE_FRAGMENT,this->fragmentShaderSource.utf8_str());
HXLINE( 133)		this->program = gs_create_program();
HXLINE( 134)		gs_program_attach_shader(this->program,this->vertexShader);
HXLINE( 135)		gs_program_attach_shader(this->program,this->fragmentShader);
HXLINE( 136)		gs_program_build(this->program);
HXLINE( 139)		this->layout = gs_create_layout();
HXLINE( 140)		{
HXLINE( 140)			 GsVtxLayout * _this = this->layout;
HXDLIN( 140)			gs_layout_add(_this,0,GS_ATTRIB_TYPE_FLOAT,3);
            		}
HXLINE( 141)		{
HXLINE( 141)			 GsVtxLayout * _this1 = this->layout;
HXDLIN( 141)			gs_layout_add(_this1,1,GS_ATTRIB_TYPE_FLOAT,2);
            		}
HXLINE( 142)		gs_layout_build(this->layout);
HXLINE( 145)		this->pipeline = gs_create_pipeline();
HXLINE( 146)		(*(this->pipeline)).layout = this->layout;
HXLINE( 147)		(*(this->pipeline)).program = this->program;
HXLINE( 148)		(*(this->pipeline)).msaa_samples = 4;
HXLINE( 151)		this->vertexBuffer = gs_create_buffer(GS_BUFFER_TYPE_VERTEX,GS_BUFFER_INTENT_DRAW_STATIC);
HXLINE( 152)		{
HXLINE( 152)			 GsBuffer * _this2 = this->vertexBuffer;
HXDLIN( 152)			::Array< float > data = this->vertexData;
HXDLIN( 152)			::cpp::Pointer< void > ptr = ( (::cpp::Pointer< float >)(::cpp::Pointer_obj::arrayElem(data,0)) )->reinterpret();
HXDLIN( 152)			 ::genesis::_GsManagedData::GsManagedDataHolder data1 = ::genesis::_GsManagedData::GsManagedData_Impl__obj::_new(ptr->ptr,(data->length * 4));
HXDLIN( 152)			gs_buffer_set_data(_this2,data1->ptr,data1->size);
            		}
HXLINE( 155)		this->indexBuffer = gs_create_buffer(GS_BUFFER_TYPE_INDEX,GS_BUFFER_INTENT_DRAW_STATIC);
HXLINE( 156)		{
HXLINE( 156)			 GsBuffer * _this3 = this->indexBuffer;
HXDLIN( 156)			::Array< int > data2 = this->indexData;
HXDLIN( 156)			::cpp::Pointer< void > ptr1 = ( (::cpp::Pointer< int >)(::cpp::Pointer_obj::arrayElem(data2,0)) )->reinterpret();
HXDLIN( 156)			 ::genesis::_GsManagedData::GsManagedDataHolder data3 = ::genesis::_GsManagedData::GsManagedData_Impl__obj::_new(ptr1->ptr,(data2->length * 4));
HXDLIN( 156)			gs_buffer_set_data(_this3,data3->ptr,data3->size);
            		}
HXLINE( 159)		this->textureUniform = gs_get_uniform_location(this->program,HX_("uTexture",e6,18,40,90).utf8_str());
HXLINE( 160)		this->timeUniform = gs_get_uniform_location(this->program,HX_("uTime",22,d7,b7,95).utf8_str());
HXLINE( 163)		 ::Dynamic imgData = linc::stb_image::load(HX_("image.png",16,96,18,16),4);
HXLINE( 164)		this->texture = gs_create_texture(( (int)(imgData->__Field(HX_("w",77,00,00,00),::hx::paccDynamic)) ),( (int)(imgData->__Field(HX_("h",68,00,00,00),::hx::paccDynamic)) ),GS_TEXTURE_FORMAT_RGBA8,GS_TEXTURE_WRAP_CLAMP,GS_TEXTURE_WRAP_CLAMP,GS_TEXTURE_FILTER_LINEAR,GS_TEXTURE_FILTER_LINEAR);
HXLINE( 165)		{
HXLINE( 165)			 GsTexture * _this4 = this->texture;
HXDLIN( 165)			{
HXLINE( 165)				::cpp::Pointer< unsigned char > ptr2 = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::arrayElem(::haxe::io::Bytes_obj::ofData(( (::Array< unsigned char >)(imgData->__Field(HX_("bytes",6b,08,98,bd),::hx::paccDynamic)) ))->b,0)) );
HXDLIN( 165)				::cpp::Pointer< void > ptr3 = ptr2->reinterpret();
HXDLIN( 165)				gs_texture_set_data(_this4,ptr3->ptr);
            			}
            		}
HXLINE( 166)		gs_texture_generate_mipmaps(this->texture);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Main_obj,initGraphics,(void))

void Main_obj::destroyGraphics(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_169_destroyGraphics)
HXLINE( 171)		gs_destroy_texture(this->texture);
HXLINE( 172)		gs_destroy_command_list(this->commandList);
HXLINE( 173)		gs_destroy_pipeline(this->pipeline);
HXLINE( 174)		gs_destroy_layout(this->layout);
HXLINE( 175)		gs_destroy_buffer(this->vertexBuffer);
HXLINE( 176)		gs_destroy_buffer(this->indexBuffer);
HXLINE( 177)		gs_destroy_shader(this->vertexShader);
HXLINE( 178)		gs_destroy_shader(this->fragmentShader);
HXLINE( 179)		gs_destroy_program(this->program);
HXLINE( 182)		gs_shutdown();
HXLINE( 185)		gs_destroy_backend(this->backend);
HXLINE( 186)		gs_destroy_config(this->config);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Main_obj,destroyGraphics,(void))

void Main_obj::frame(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_189_frame)
HXLINE( 190)		{
HXLINE( 190)			 GsCommandList * _this = this->commandList;
HXDLIN( 190)			gs_command_list_begin(_this);
            		}
HXLINE( 191)		{
HXLINE( 191)			 GsCommandList * _this1 = this->commandList;
HXDLIN( 191)			gs_set_viewport(_this1,0,0,600,600);
            		}
HXLINE( 192)		{
HXLINE( 192)			 GsCommandList * _this2 = this->commandList;
HXDLIN( 192)			gs_clear(_this2,(GsClearFlags)(1 | 2),( (Float)(0) ),( (Float)(0) ),( (Float)(0) ),( (Float)(1) ));
            		}
HXLINE( 193)		{
HXLINE( 193)			 GsCommandList * _this3 = this->commandList;
HXDLIN( 193)			gs_use_pipeline(_this3,this->pipeline);
            		}
HXLINE( 194)		{
HXLINE( 194)			 GsCommandList * _this4 = this->commandList;
HXDLIN( 194)			gs_uniform_set_int(_this4,this->textureUniform,0);
            		}
HXLINE( 195)		{
HXLINE( 195)			 GsCommandList * _this5 = this->commandList;
HXDLIN( 195)			int location = this->timeUniform;
HXDLIN( 195)			gs_uniform_set_int(_this5,location,::Std_obj::_hx_int((::Sys_obj::time() * ( (Float)(1000) ))));
            		}
HXLINE( 196)		{
HXLINE( 196)			 GsCommandList * _this6 = this->commandList;
HXDLIN( 196)			gs_use_buffer(_this6,this->vertexBuffer);
            		}
HXLINE( 197)		{
HXLINE( 197)			 GsCommandList * _this7 = this->commandList;
HXDLIN( 197)			gs_use_buffer(_this7,this->indexBuffer);
            		}
HXLINE( 198)		{
HXLINE( 198)			 GsCommandList * _this8 = this->commandList;
HXDLIN( 198)			gs_use_texture(_this8,this->texture,0);
            		}
HXLINE( 199)		{
HXLINE( 199)			 GsCommandList * _this9 = this->commandList;
HXDLIN( 199)			gs_draw_indexed(_this9,6);
            		}
HXLINE( 200)		{
HXLINE( 200)			 GsCommandList * _this10 = this->commandList;
HXDLIN( 200)			gs_command_list_end(_this10);
            		}
HXLINE( 201)		{
HXLINE( 201)			 GsCommandList * _this11 = this->commandList;
HXDLIN( 201)			gs_command_list_submit(_this11);
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC0(Main_obj,frame,(void))

void Main_obj::loop(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_204_loop)
HXLINE( 205)		::cpp::Pointer<  GLFWwindow > tmp = this->window;
HXDLIN( 205)		if ((glfwWindowShouldClose(tmp) == 1)) {
HXLINE( 206)			this->destroy();
HXLINE( 207)			return;
            		}
HXLINE( 210)		this->frame();
HXLINE( 212)		gs_frame();
HXLINE( 213)		::cpp::Pointer<  GLFWwindow > tmp1 = this->window;
HXDLIN( 213)		glfwSwapBuffers(tmp1);
HXLINE( 214)		glfwPollEvents();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Main_obj,loop,(void))

void Main_obj::init(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_217_init)
HXLINE( 218)		this->initWindow();
HXLINE( 219)		this->initGraphics();
HXLINE( 221)		::genesis::GsMainloop_obj::start(this->loop_dyn());
            	}


HX_DEFINE_DYNAMIC_FUNC0(Main_obj,init,(void))

void Main_obj::destroy(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_224_destroy)
HXLINE( 225)		gs_stop_mainloop();
HXLINE( 226)		this->destroyGraphics();
HXLINE( 227)		this->destroyWindow();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Main_obj,destroy,(void))

void Main_obj::main(){
            	HX_GC_STACKFRAME(&_hx_pos_e47a9afac0942eb9_230_main)
HXLINE( 231)		 ::Main app =  ::Main_obj::__alloc( HX_CTX );
HXLINE( 232)		app->init();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(Main_obj,main,(void))


::hx::ObjectPtr< Main_obj > Main_obj::__new() {
	::hx::ObjectPtr< Main_obj > __this = new Main_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< Main_obj > Main_obj::__alloc(::hx::Ctx *_hx_ctx) {
	Main_obj *__this = (Main_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Main_obj), true, "Main"));
	*(void **)__this = Main_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

Main_obj::Main_obj()
{
}

void Main_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Main);
	HX_MARK_MEMBER_NAME(vertexData,"vertexData");
	HX_MARK_MEMBER_NAME(indexData,"indexData");
	HX_MARK_MEMBER_NAME(vertexShaderSource,"vertexShaderSource");
	HX_MARK_MEMBER_NAME(fragmentShaderSource,"fragmentShaderSource");
	HX_MARK_MEMBER_NAME(window,"window");
	HX_MARK_MEMBER_NAME(backend,"backend");
	HX_MARK_MEMBER_NAME(config,"config");
	HX_MARK_MEMBER_NAME(commandList,"commandList");
	HX_MARK_MEMBER_NAME(pipeline,"pipeline");
	HX_MARK_MEMBER_NAME(layout,"layout");
	HX_MARK_MEMBER_NAME(program,"program");
	HX_MARK_MEMBER_NAME(vertexShader,"vertexShader");
	HX_MARK_MEMBER_NAME(fragmentShader,"fragmentShader");
	HX_MARK_MEMBER_NAME(vertexBuffer,"vertexBuffer");
	HX_MARK_MEMBER_NAME(indexBuffer,"indexBuffer");
	HX_MARK_MEMBER_NAME(textureUniform,"textureUniform");
	HX_MARK_MEMBER_NAME(timeUniform,"timeUniform");
	HX_MARK_MEMBER_NAME(texture,"texture");
	HX_MARK_END_CLASS();
}

void Main_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(vertexData,"vertexData");
	HX_VISIT_MEMBER_NAME(indexData,"indexData");
	HX_VISIT_MEMBER_NAME(vertexShaderSource,"vertexShaderSource");
	HX_VISIT_MEMBER_NAME(fragmentShaderSource,"fragmentShaderSource");
	HX_VISIT_MEMBER_NAME(window,"window");
	HX_VISIT_MEMBER_NAME(backend,"backend");
	HX_VISIT_MEMBER_NAME(config,"config");
	HX_VISIT_MEMBER_NAME(commandList,"commandList");
	HX_VISIT_MEMBER_NAME(pipeline,"pipeline");
	HX_VISIT_MEMBER_NAME(layout,"layout");
	HX_VISIT_MEMBER_NAME(program,"program");
	HX_VISIT_MEMBER_NAME(vertexShader,"vertexShader");
	HX_VISIT_MEMBER_NAME(fragmentShader,"fragmentShader");
	HX_VISIT_MEMBER_NAME(vertexBuffer,"vertexBuffer");
	HX_VISIT_MEMBER_NAME(indexBuffer,"indexBuffer");
	HX_VISIT_MEMBER_NAME(textureUniform,"textureUniform");
	HX_VISIT_MEMBER_NAME(timeUniform,"timeUniform");
	HX_VISIT_MEMBER_NAME(texture,"texture");
}

::hx::Val Main_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"loop") ) { return ::hx::Val( loop_dyn() ); }
		if (HX_FIELD_EQ(inName,"init") ) { return ::hx::Val( init_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"frame") ) { return ::hx::Val( frame_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"window") ) { return ::hx::Val( window ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"destroy") ) { return ::hx::Val( destroy_dyn() ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"indexData") ) { return ::hx::Val( indexData ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"vertexData") ) { return ::hx::Val( vertexData ); }
		if (HX_FIELD_EQ(inName,"initWindow") ) { return ::hx::Val( initWindow_dyn() ); }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"timeUniform") ) { return ::hx::Val( timeUniform ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"initGraphics") ) { return ::hx::Val( initGraphics_dyn() ); }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"destroyWindow") ) { return ::hx::Val( destroyWindow_dyn() ); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"textureUniform") ) { return ::hx::Val( textureUniform ); }
		break;
	case 15:
		if (HX_FIELD_EQ(inName,"destroyGraphics") ) { return ::hx::Val( destroyGraphics_dyn() ); }
		break;
	case 18:
		if (HX_FIELD_EQ(inName,"vertexShaderSource") ) { return ::hx::Val( vertexShaderSource ); }
		break;
	case 20:
		if (HX_FIELD_EQ(inName,"fragmentShaderSource") ) { return ::hx::Val( fragmentShaderSource ); }
	}
	return super::__Field(inName,inCallProp);
}

bool Main_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

::hx::Val Main_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"window") ) { window=inValue.Cast< ::cpp::Pointer<  GLFWwindow > >(); return inValue; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"indexData") ) { indexData=inValue.Cast< ::Array< int > >(); return inValue; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"vertexData") ) { vertexData=inValue.Cast< ::Array< float > >(); return inValue; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"timeUniform") ) { timeUniform=inValue.Cast< int >(); return inValue; }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"textureUniform") ) { textureUniform=inValue.Cast< int >(); return inValue; }
		break;
	case 18:
		if (HX_FIELD_EQ(inName,"vertexShaderSource") ) { vertexShaderSource=inValue.Cast< ::String >(); return inValue; }
		break;
	case 20:
		if (HX_FIELD_EQ(inName,"fragmentShaderSource") ) { fragmentShaderSource=inValue.Cast< ::String >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Main_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("vertexData",ae,df,1f,d3));
	outFields->push(HX_("indexData",5c,0e,71,fe));
	outFields->push(HX_("vertexShaderSource",64,fb,81,44));
	outFields->push(HX_("fragmentShaderSource",d0,71,8a,f6));
	outFields->push(HX_("window",f0,93,8c,52));
	outFields->push(HX_("backend",14,bc,87,fb));
	outFields->push(HX_("config",c2,56,d2,c7));
	outFields->push(HX_("commandList",49,bb,13,e5));
	outFields->push(HX_("pipeline",22,bb,83,4b));
	outFields->push(HX_("layout",aa,ae,b8,58));
	outFields->push(HX_("program",84,4a,f9,f3));
	outFields->push(HX_("vertexShader",a9,b1,35,bd));
	outFields->push(HX_("fragmentShader",15,4f,dc,39));
	outFields->push(HX_("vertexBuffer",84,af,a9,70));
	outFields->push(HX_("indexBuffer",b2,65,a6,f5));
	outFields->push(HX_("textureUniform",99,41,25,d7));
	outFields->push(HX_("timeUniform",a7,e8,b9,27));
	outFields->push(HX_("texture",db,c8,e0,9e));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Main_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /* ::Array< float > */ ,(int)offsetof(Main_obj,vertexData),HX_("vertexData",ae,df,1f,d3)},
	{::hx::fsObject /* ::Array< int > */ ,(int)offsetof(Main_obj,indexData),HX_("indexData",5c,0e,71,fe)},
	{::hx::fsString,(int)offsetof(Main_obj,vertexShaderSource),HX_("vertexShaderSource",64,fb,81,44)},
	{::hx::fsString,(int)offsetof(Main_obj,fragmentShaderSource),HX_("fragmentShaderSource",d0,71,8a,f6)},
	{::hx::fsUnknown /* ::cpp::Pointer<  GLFWwindow > */ ,(int)offsetof(Main_obj,window),HX_("window",f0,93,8c,52)},
	{::hx::fsUnknown /*  GsBackend * */ ,(int)offsetof(Main_obj,backend),HX_("backend",14,bc,87,fb)},
	{::hx::fsUnknown /*  GsConfig * */ ,(int)offsetof(Main_obj,config),HX_("config",c2,56,d2,c7)},
	{::hx::fsUnknown /*  GsCommandList * */ ,(int)offsetof(Main_obj,commandList),HX_("commandList",49,bb,13,e5)},
	{::hx::fsUnknown /*  GsPipeline * */ ,(int)offsetof(Main_obj,pipeline),HX_("pipeline",22,bb,83,4b)},
	{::hx::fsUnknown /*  GsVtxLayout * */ ,(int)offsetof(Main_obj,layout),HX_("layout",aa,ae,b8,58)},
	{::hx::fsUnknown /*  GsProgram * */ ,(int)offsetof(Main_obj,program),HX_("program",84,4a,f9,f3)},
	{::hx::fsUnknown /*  GsShader * */ ,(int)offsetof(Main_obj,vertexShader),HX_("vertexShader",a9,b1,35,bd)},
	{::hx::fsUnknown /*  GsShader * */ ,(int)offsetof(Main_obj,fragmentShader),HX_("fragmentShader",15,4f,dc,39)},
	{::hx::fsUnknown /*  GsBuffer * */ ,(int)offsetof(Main_obj,vertexBuffer),HX_("vertexBuffer",84,af,a9,70)},
	{::hx::fsUnknown /*  GsBuffer * */ ,(int)offsetof(Main_obj,indexBuffer),HX_("indexBuffer",b2,65,a6,f5)},
	{::hx::fsInt,(int)offsetof(Main_obj,textureUniform),HX_("textureUniform",99,41,25,d7)},
	{::hx::fsInt,(int)offsetof(Main_obj,timeUniform),HX_("timeUniform",a7,e8,b9,27)},
	{::hx::fsUnknown /*  GsTexture * */ ,(int)offsetof(Main_obj,texture),HX_("texture",db,c8,e0,9e)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *Main_obj_sStaticStorageInfo = 0;
#endif

static ::String Main_obj_sMemberFields[] = {
	HX_("vertexData",ae,df,1f,d3),
	HX_("indexData",5c,0e,71,fe),
	HX_("vertexShaderSource",64,fb,81,44),
	HX_("fragmentShaderSource",d0,71,8a,f6),
	HX_("window",f0,93,8c,52),
	HX_("textureUniform",99,41,25,d7),
	HX_("timeUniform",a7,e8,b9,27),
	HX_("initWindow",20,ef,d1,56),
	HX_("destroyWindow",8a,2c,86,20),
	HX_("initGraphics",fb,7f,1e,b7),
	HX_("destroyGraphics",e5,6b,6c,84),
	HX_("frame",2d,78,83,06),
	HX_("loop",64,a6,b7,47),
	HX_("init",10,3b,bb,45),
	HX_("destroy",fa,2c,86,24),
	::String(null()) };

::hx::Class Main_obj::__mClass;

static ::String Main_obj_sStaticFields[] = {
	HX_("main",39,38,56,48),
	::String(null())
};

void Main_obj::__register()
{
	Main_obj _hx_dummy;
	Main_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("Main",59,64,2f,33);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Main_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Main_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Main_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Main_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Main_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Main_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

