// Generated by Haxe 4.3.3
#include <hxcpp.h>

#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_glfw_GLFWWindowSizeHandler
#include <glfw/GLFWWindowSizeHandler.h>
#endif
#ifndef INCLUDED_glfw_GLFWMouseWheelHandler
#include <glfw/GLFWMouseWheelHandler.h>
#endif
#ifndef INCLUDED_glfw_GLFWMouseButtonHandler
#include <glfw/GLFWMouseButtonHandler.h>
#endif
#ifndef INCLUDED_glfw_GLFWMouseMoveHandler
#include <glfw/GLFWMouseMoveHandler.h>
#endif
#ifndef INCLUDED_glfw_GLFWKeyHandler
#include <glfw/GLFWKeyHandler.h>
#endif
#ifndef INCLUDED_glfw_GLFWCharHandler
#include <glfw/GLFWCharHandler.h>
#endif
#ifndef INCLUDED_sys_io_File
#include <sys/io/File.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_io_Path
#include <haxe/io/Path.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_glfw_GLFWJoystickHandler
#include <glfw/GLFWJoystickHandler.h>
#endif
#ifndef INCLUDED_glfw_GLFWErrorHandler
#include <glfw/GLFWErrorHandler.h>
#endif
#ifndef INCLUDED_genesis__GsManagedData_GsManagedData_Impl_
#include <genesis/_GsManagedData/GsManagedData_Impl_.h>
#endif
#ifndef INCLUDED_genesis__GsManagedData_GsManagedDataHolder
#include <genesis/_GsManagedData/GsManagedDataHolder.h>
#endif
#ifndef INCLUDED_genesis_GsMainloop
#include <genesis/GsMainloop.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Main
#include <Main.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::haxe::Log_obj::__register();
::glfw::GLFWWindowSizeHandler_obj::__register();
::glfw::GLFWMouseWheelHandler_obj::__register();
::glfw::GLFWMouseButtonHandler_obj::__register();
::glfw::GLFWMouseMoveHandler_obj::__register();
::glfw::GLFWKeyHandler_obj::__register();
::glfw::GLFWCharHandler_obj::__register();
::sys::io::File_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::io::Path_obj::__register();
::haxe::io::Bytes_obj::__register();
::haxe::ds::StringMap_obj::__register();
::glfw::GLFWJoystickHandler_obj::__register();
::glfw::GLFWErrorHandler_obj::__register();
::genesis::_GsManagedData::GsManagedData_Impl__obj::__register();
::genesis::_GsManagedData::GsManagedDataHolder_obj::__register();
::genesis::GsMainloop_obj::__register();
::haxe::IMap_obj::__register();
::Sys_obj::__register();
::StringBuf_obj::__register();
::Std_obj::__register();
::Main_obj::__register();
::haxe::Log_obj::__boot();
::glfw::GLFWCharHandler_obj::__boot();
::glfw::GLFWKeyHandler_obj::__boot();
::glfw::GLFWMouseMoveHandler_obj::__boot();
::glfw::GLFWMouseButtonHandler_obj::__boot();
::glfw::GLFWMouseWheelHandler_obj::__boot();
::glfw::GLFWWindowSizeHandler_obj::__boot();
}

